### ISSUE TITLE
Parser training failure following README instructions

### ISSUE THREAD

**Issue by StefPac** [danielhers/tupa#3]
Hi, 

I followed the instructions in the README to train the _tupa_ parser on the linked Wiki dataset (tried both xml and pickle formatted), that I split using the `split_corpus.py` script from the `ucca` repository (also linked in the page).

I ran this command (for the pickled files):
```
python -m tupa.parse -t ucca-corpus/wiki/pickle/train/ -d ucca-corpus/wiki/pickle/dev/ -c bilstm -m 2017-08-22-bilstm
```
which failed in the first iteration of the training, with an `IndexError: tuple index out of range`. Same error and stack trace for the XML files. 

The full trace is below. Any help to reproduce the results is appreciated, thanks!

```
python -m tupa.parse -t ucca-corpus/wiki/pickle/train/ -d ucca-corpus/wiki/pickle/dev/ -c bilstm -m 2017-08-22-bilstm
[dynet] random seed: 1
[dynet] allocating memory: 512MB
[dynet] memory allocation done.

    Warning: no model found for 'en'

    Only loading the 'en' tokenizer.

parse.py --action-dim 5 --activation sigmoid --beam 1 --no-check-loops --classifier bilstm --constraints --constructions primary remote --dep-dim 10 --dev ucca-corpus/wiki/pickle/dev/ --devsc
ores 2017-08-22-bilstm.dev.csv --dropout 0.5 --no-dynet-autobatch --no-dynet-gpu --dynet-gpus 1 --no-dynet-viz --dynet-weight-decay 1e-06 --no-early-update --edge-label-dim 20 --embedding-lay
er-dim 500 --embedding-layers 1 --no-evaluate --no-implicit --init glorot_uniform --iterations 1 --layer-dim 500 --layers 2 --learning-rate-decay 0.0 --no-linkage --log 2017-08-22-bilstm.log 
--lstm-layer-dim 500 --lstm-layers 2 --max-action-labels 100 --max-action-ratio 100 --max-action-types 10 --max-deps 100 --max-edge-labels 15 --max-height 20 --max-length 120 --max-ner-types 
18 --max-node-ratio 10 --max-puncts 5 --max-tags 100 --max-words 10000 --minibatch-size 200 --model 2017-08-22-bilstm --ner-dim 5 --optimizer adam --orphan-label orphan --outdir . --output-di
m 50 --no-paragraphs --punct-dim 2 --remote --no-require-connected --seed 1 --no-sentences --swap regular --swap-importance 1 --tag-dim 10 --train ucca-corpus/wiki/pickle/train/ --no-update-w
ord-vectors --verbose 0 --no-verify --no-wikification --word-dim 100 --word-dim-external 300 --word-dropout 0.25 --word-dropout-external 0.25 --write
Loading from '2017-08-22-bilstm.enum'... not found, starting from untrained model.
Training iteration 1 of 1: 
passage 250     Traceback (most recent call last):
  File "/users2/spacific/anaconda3/envs/dynet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "anaconda3/envs/dynet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/parse.py", line 438, in <module>
    list(main())
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/parse.py", line 434, in main
    yield from train_test(train_passages, dev_passages, test_passages, args)
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/parse.py", line 354, in train_test
    yield from filter(None, p.train(train_passages, dev=dev_passages, iterations=args.iterations))
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/parse.py", line 69, in train
    list(self.parse(passages, mode=ParseMode.train))
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/parse.py", line 149, in parse
    self.model.init_features(self.state, train)
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/model.py", line 75, in init_features
    self.model.init_features(self.feature_extractor.init_features(state), train)
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/classifiers/nn/bilstm.py", line 38, in init_features
    self.init_model()
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/classifiers/nn/neural_network.py", line 87, in init_model
    self.init_input_params()
  File "anaconda3/envs/dynet/lib/python3.6/site-packages/tupa/classifiers/nn/neural_network.py", line 105, in init_input_params
    p.init_from_array(param.init)
  File "_dynet.pyx", line 678, in _dynet.LookupParameters.init_from_array
  File "_dynet.pyx", line 681, in _dynet.LookupParameters.init_from_array
IndexError: tuple index out of range
```

**Comment by danielhers** [comment]
I believe the problem is that the spaCy model is missing. Please try:

    python -m spacy download en

And try again.

**Comment by StefPac** [comment]
Thanks it did work. I'll make a change to the README and submit a PR.
