### ISSUE TITLE
AttributeError: module 'ucca.convert' has no attribute 'FormatConverter'

### ISSUE THREAD

**Issue by feralvam** [danielhers/tupa#34]
Hi,
I installed the tupa package using `pip` and downloaded the pre-trained models for English. Then I created a simple text file with just one sentence and run (as shown in the README): 

`python -m tupa example.txt -m models/ucca-bilstm`

I got the following error message:  

```
Traceback (most recent call last):
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/site-packages/tupa/__main__.py", line 1, in <module>
    from .parse import *
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/site-packages/tupa/parse.py", line 10, in <module>
    from semstr.convert import FROM_FORMAT, TO_FORMAT
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/site-packages/semstr/convert.py", line 15, in <module>
    from semstr.conversion.amr import from_amr, to_amr
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/site-packages/semstr/conversion/amr.py", line 11, in <module>
    class AmrConverter(convert.FormatConverter):
AttributeError: module 'ucca.convert' has no attribute 'FormatConverter'
```

Any idea what could be causing this error? Thank you.

**Comment by danielhers** [comment]
Sorry, there was a version compatibility problem with some of the requirements. Please upgrade to 1.3.3 and try again:

    pip install tupa==1.3.3

**Comment by feralvam** [comment]
Hi,
That solved that particular error. But now I get another one: 
```
FileNotFoundError: [Errno 2] No such file or directory: 'vocab/en_core_web_lg.csv'
```
Where should I get that file from? Would it be better to open a new issue?

**Comment by danielhers** [comment]
Sorry, that shouldn't have happened. Until I fix it, please generate the vocabulary file before running TUPA using the following commands:

    mkdir vocab
    python -m tupa.scripts.dump_vocab en_core_web_lg vocab/en_core_web_lg.csv
