### ISSUE TITLE
Parser import bug in latest release?

### ISSUE THREAD

**Issue by borgr** [danielhers/tupa#38]
I installed a clean version of tupa and tried to import Parser:

`
>>> from tupa.parse import Parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cs/labs/oabend/borgr/envs/USim/lib/python3.5/site-packages/tupa/parse.py", line 11, in <module>
    from semstr.evaluate import EVALUATORS, Scores
  File "/cs/labs/oabend/borgr/envs/USim/lib/python3.5/site-packages/semstr/evaluate.py", line 16, in <module>
    from semstr.evaluation import amr, sdp, conllu
  File "/cs/labs/oabend/borgr/envs/USim/lib/python3.5/site-packages/semstr/evaluation/amr.py", line 9, in <module>
    sys.path.insert(0, os.path.dirname(importlib.util.find_spec("smatch.smatch").origin))  # to find amr.py from smatch
AttributeError: module 'importlib' has no attribute 'util'
`

**Comment by danielhers** [comment]
Should be fixed by https://github.com/danielhers/semstr/commit/26d8316455eafba7dbec630dbdeff94cf5fa69bc - will be in next release.

**Comment by danielhers** [comment]
Fixed in [1.3.6](https://pypi.org/project/TUPA/1.3.6/) - please verify.
