### ISSUE TITLE
Unable to run parser: KeyError: None

### ISSUE THREAD

**Issue by around1991** [danielhers/tupa#7]
Hi guys

Thanks so much for releasing this parser! I've been exploring different semantic parsers, and I think UCCA seems very close to what I want :).

I'm trying to run the parser, and I've installed tupa from pip, and downloaded the pre-trained model files. However, when I try to parse a sentence, I get the following error:

```env/bin/python -m tupa.parse example.txt -c bilstm -m models/bilstm
[dynet] random seed: 1
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Loading from 'models/bilstm.enum'... Done (5.300s).
Loading from 'models/bilstm.json'... Done (0.001s).
Loading model from 'models/bilstm'... Done (54.411s).
parse.py example.txt --action-dim 3 --activation relu --beam 1 --no-check-loops --classifier bilstm --constraints --constructions primary remote --dep-dim 10 --dep-dropout 0.2 --dropout 0.4 --no-dynet-autobatch --no-dynet-gpu --dynet-gpus 1 --no-dynet-viz --dynet-weight-decay 1e-05 --no-early-update --edge-label-dim 20 --embedding-layer-dim 500 --embedding-layers 1 --no-evaluate --hyperparams "shared --lstm-layers 2" --init glorot_uniform --iterations 1 --layer-dim 50 --layers 2 --learning-rate-decay 0.0 --log models/bilstm.log --lstm-layer-dim 500 --lstm-layers 0 --max-action-labels 100 --max-action-ratio 100 --max-action-types 10 --max-deps 100 --max-edge-labels 15 --max-height 20 --max-length 120 --max-ner-types 18 --max-node-ratio 10 --max-puncts 5 --max-tags 100 --max-words 10000 --max-words-external 798844 --minibatch-size 100 --model models/bilstm --ner-dim 5 --optimizer adam --orphan-label orphan --outdir . --output-dim 50 --no-paragraphs --punct-dim 1 --remote --rnn lstm --seed 1 --no-sentences --swap regular --swap-importance 1 --tag-dim 20 --tag-dropout 0.2 --testscores models/bilstm.test.csv --update-word-vectors --verbose 0 --no-verify --word-dim 200 --word-dim-external 100 --word-dropout 0.2 --word-dropout-external 0.0 --word-vectors word_vectors/sskip.100.vectors.txt --write
  0%|                                                                                                                                                               | 0/1 [00:00<?, ?passage/s]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/auto/homes/kc391/synsem/env/lib/python3.5/site-packages/tupa/parse.py", line 496, in <module>
    list(main())
  File "/auto/homes/kc391/synsem/env/lib/python3.5/site-packages/tupa/parse.py", line 481, in main
    yield from train_test(train_passages, dev_passages, test_passages, args)
  File "/auto/homes/kc391/synsem/env/lib/python3.5/site-packages/tupa/parse.py", line 383, in train_test
    for result in p.parse(test_passages, evaluate=evaluate):
  File "/auto/homes/kc391/synsem/env/lib/python3.5/site-packages/tupa/parse.py", line 162, in parse
    self.model.init_features(self.state, axes, self.training)
  File "/auto/homes/kc391/synsem/env/lib/python3.5/site-packages/tupa/model.py", line 129, in init_features
    self.classifier.init_features(self.feature_extractor.init_features(state), axes, train)
  File "/auto/homes/kc391/synsem/env/lib/python3.5/site-packages/tupa/classifiers/nn/neural_network.py", line 117, in init_features
    self.axes[axis].birnn.init_features(features, train)
KeyError: None
```

do you know what could be causing this?

Thanks!
Kris

**Comment by danielhers** [comment]
Thanks! Fixed in 1.2.4.
